- id: "conda_check_env"
  name: "Conda check env"
  entry: conda_check_env.sh
  types: [file]
  exclude: ".yaml$|.yml$"
  language: "script"
  description: "Check existence of env.yaml"
- id: "conda_check_deps"
  name: "Conda check dependencies"
  entry: conda_check_deps.sh
  types: [file]
  language: "script"
  description: "Check that there is the same number of modules in env.yaml as in the env folder."
- id: run_pytest
  name: "Run Pytest"
  entry: run_pytest.py
  types: [python]
  language: "conda"
  description: "Run all tests."
