- id: "conda_check_env"
  name: "Conda check env"
  entry: conda_check_env.sh
  types: [file]
  exclude: ".yaml$|.yml$"
  language: "script"
  description: "Check existence of env.yaml"
  verbose: true

